<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"zh-CN\">";
echo "<head>";
echo "    <meta charset=\"UTF-8\">";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
echo "    <title>Ai 图像生成</title>";
echo "    <script src=\"https://cdn.tailwindcss.com\"></script>";
echo "    <link href=\"https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">";
echo "    <script>";
echo "        tailwind.config = {";
echo "            theme: {";
echo "                extend: {";
echo "                    colors: {";
echo "                        primary: \'#165DFF\',";
echo "                        secondary: \'#722ED1\',";
echo "                        dark: \'#1D2129\',";
echo "                        light: \'#F2F3F5\'";
echo "                    },";
echo "                    fontFamily: {";
echo "                        inter: [\'Inter\', \'sans-serif\'],";
echo "                    },";
echo "                }";
echo "            }";
echo "        }";
echo "    </script>";
echo "    <style type=\"text/tailwindcss\">";
echo "        @layer utilities {";
echo "            .content-auto {";
echo "                content-visibility: auto;";
echo "            }";
echo "            .text-shadow {";
echo "                text-shadow: 0 2px 4px rgba(0,0,0,0.1);";
echo "            }";
echo "            .bg-gradient-primary {";
echo "                background: linear-gradient(135deg, #165DFF 0%, #722ED1 100%);";
echo "            }";
echo "        }";
echo "    </style>";
echo "</head>";
echo "<body class=\"bg-gray-100 font-inter text-dark min-h-screen flex flex-col\">";
echo "    <header class=\"bg-gradient-primary text-white shadow-lg\">";
echo "        <div class=\"container mx-auto px-4 py-6\">";
echo "            <h1 class=\"text-[clamp(1.5rem,3vw,2.5rem)] font-bold text-shadow\">";
echo "                <i class=\"fa fa-paint-brush mr-2\"></i>Ai 图像生成";
echo "            </h1>";
echo "            <p class=\"text-blue-100 mt-2\">基于AI的图像生成工具</p>";
echo "        </div>";
echo "    </header>";
echo "";
echo "    <main class=\"flex-grow container mx-auto px-4 py-8\">";
echo "        <div class=\"grid grid-cols-1 lg:grid-cols-3 gap-8\">";
echo "            <div class=\"lg:col-span-1\">";
echo "                <div class=\"bg-white rounded-xl shadow-md p-6 sticky top-8\">";
echo "                    <h2 class=\"text-xl font-semibold mb-4 flex items-center\">";
echo "                        <i class=\"fa fa-sliders text-primary mr-2\"></i>参数设置";
echo "                    </h2>";
echo "                    <form id=\"generationForm\" class=\"space-y-4\">";
echo "                        <div>";
echo "                            <label for=\"prompt\" class=\"block text-sm font-medium text-gray-700 mb-1\">提示词 (Prompt)</label>";
echo "                            <textarea id=\"prompt\" name=\"prompt\" rows=\"4\" class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all\" placeholder=\"描述你想要生成的图像...\">girl</textarea>";
echo "                        </div>";
echo "";
echo "                        <div class=\"grid grid-cols-1 sm:grid-cols-2 gap-4\">";
echo "                            <div>";
echo "                                <label for=\"width\" class=\"block text-sm font-medium text-gray-700 mb-1\">宽度 (Width)</label>";
echo "                                <input type=\"number\" id=\"width\" name=\"width\" value=\"1024\" min=\"256\" max=\"2048\" step=\"64\" class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all\">";
echo "                            </div>";
echo "                            <div>";
echo "                                <label for=\"height\" class=\"block text-sm font-medium text-gray-700 mb-1\">高度 (Height)</label>";
echo "                                <input type=\"number\" id=\"height\" name=\"height\" value=\"1024\" min=\"256\" max=\"2048\" step=\"64\" class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all\">";
echo "                            </div>";
echo "                        </div>";
echo "";
echo "                        <div class=\"grid grid-cols-1 sm:grid-cols-2 gap-4\">";
echo "                            <div>";
echo "                                <label for=\"steps\" class=\"block text-sm font-medium text-gray-700 mb-1\">步数 (Steps)</label>";
echo "                                <input type=\"number\" id=\"steps\" name=\"steps\" value=\"30\" min=\"1\" max=\"100\" class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all\">";
echo "                            </div>";
echo "                            <div>";
echo "                                <label for=\"seed\" class=\"block text-sm font-medium text-gray-700 mb-1\">随机种子 (Seed)</label>";
echo "                                <input type=\"number\" id=\"seed\" name=\"seed\" value=\"20613403\" class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all\">";
echo "                            </div>";
echo "                        </div>";
echo "";
echo "                        <div class=\"grid grid-cols-1 sm:grid-cols-2 gap-4\">";
echo "                            <div>";
echo "                                <label for=\"batch_size\" class=\"block text-sm font-medium text-gray-700 mb-1\">批量大小</label>";
echo "                                <input type=\"number\" id=\"batch_size\" name=\"batch_size\" value=\"1\" min=\"1\" max=\"8\" class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all\">";
echo "                            </div>";
echo "                            <div>";
echo "                                <label for=\"model\" class=\"block text-sm font-medium text-gray-700 mb-1\">模型 (Model)</label>";
echo "                                <select id=\"model\" name=\"model\" class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all\">";
echo "                                    <!-- 模型选项将通过JavaScript动态加载 -->";
echo "                                </select>";
echo "                            </div>";
echo "                        </div>";
echo "";
echo "                        <div class=\"pt-2\">";
echo "                            <button type=\"button\" id=\"randomSeedBtn\" class=\"text-sm text-primary hover:text-primary/80 transition-colors\">";
echo "                                <i class=\"fa fa-random mr-1\"></i> 随机种子";
echo "                            </button>";
echo "                        </div>";
echo "";
echo "                        <div class=\"pt-4\">";
echo "                            <button type=\"submit\" id=\"generateBtn\" class=\"w-full bg-primary hover:bg-primary/90 text-white font-medium py-3 px-4 rounded-lg transition-all duration-300 flex items-center justify-center\">";
echo "                                <i class=\"fa fa-magic mr-2\"></i> 生成图像";
echo "                            </button>";
echo "                        </div>";
echo "                    </form>";
echo "                </div>";
echo "            </div>";
echo "";
echo "            <div class=\"lg:col-span-2\">";
echo "                <div class=\"bg-white rounded-xl shadow-md p-6 mb-6\">";
echo "                    <h2 class=\"text-xl font-semibold mb-4 flex items-center\">";
echo "                        <i class=\"fa fa-image text-primary mr-2\"></i>生成结果";
echo "                    </h2>";
echo "                    <div id=\"loadingIndicator\" class=\"hidden flex justify-center items-center py-12\">";
echo "                        <div class=\"animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary\"></div>";
echo "                        <p class=\"ml-4 text-gray-500\">正在生成图像，请稍候...</p>";
echo "                    </div>";
echo "                    <div id=\"resultContainer\" class=\"hidden\">";
echo "                        <div class=\"relative mb-4\">";
echo "                            <img id=\"generatedImage\" src=\"\" alt=\"生成的图像\" class=\"w-full h-auto rounded-lg shadow-md\">";
echo "                            <button id=\"downloadBtn\" class=\"absolute bottom-4 right-4 bg-white/80 hover:bg-white text-primary font-medium py-2 px-4 rounded-lg backdrop-blur-sm transition-all flex items-center\">";
echo "                                <i class=\"fa fa-download mr-1\"></i> 下载";
echo "                            </button>";
echo "                        </div>";
echo "                        <div class=\"bg-gray-50 p-4 rounded-lg\">";
echo "                            <h3 class=\"font-medium mb-2\">提示词</h3>";
echo "                            <p id=\"resultPrompt\" class=\"text-gray-700\"></p>";
echo "                        </div>";
echo "                    </div>";
echo "                    <div id=\"errorContainer\" class=\"hidden bg-red-50 border border-red-200 p-4 rounded-lg mt-4\">";
echo "                        <div class=\"flex items-start\">";
echo "                            <div class=\"flex-shrink-0 pt-0.5\">";
echo "                                <i class=\"fa fa-exclamation-circle text-red-500\"></i>";
echo "                            </div>";
echo "                            <div class=\"ml-3\">";
echo "                                <h3 class=\"text-sm font-medium text-red-800\">生成失败</h3>";
echo "                                <div class=\"mt-2 text-sm text-red-700\">";
echo "                                    <p id=\"errorMessage\"></p>";
echo "                                </div>";
echo "                            </div>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "";
echo "                <div class=\"bg-white rounded-xl shadow-md p-6\">";
echo "                    <h2 class=\"text-xl font-semibold mb-4 flex items-center\">";
echo "                        <i class=\"fa fa-history text-primary mr-2\"></i>历史记录";
echo "                    </h2>";
echo "                    <div id=\"historyContainer\" class=\"space-y-4\">";
echo "                        <!-- 历史记录将通过JavaScript动态加载 -->";
echo "                        <div class=\"text-center text-gray-500 py-8\">";
echo "                            <i class=\"fa fa-clock-o text-3xl mb-2\"></i>";
echo "                            <p>暂无生成历史</p>";
echo "                        </div>";
echo "                    </div>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </main>";
echo "";
echo "    <footer class=\"bg-dark text-white py-6 mt-8\">";
echo "        <div class=\"container mx-auto px-4\">";
echo "            <div class=\"flex flex-col md:flex-row justify-between items-center\">";
echo "                <div class=\"mb-4 md:mb-0\">";
echo "                    <p>© 2025 Tawer 图像生成工具</p>";
echo "                </div>";
echo "                <div class=\"flex space-x-4\">";
echo "                    <a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">";
echo "                        <i class=\"fa fa-github\"></i>";
echo "                    </a>";
echo "                    <a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">";
echo "                        <i class=\"fa fa-twitter\"></i>";
echo "                    </a>";
echo "                    <a href=\"#\" class=\"text-gray-300 hover:text-white transition-colors\">";
echo "                        <i class=\"fa fa-envelope\"></i>";
echo "                    </a>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </footer>";
echo "";
echo "    <script>";
echo "        // 从config.php获取模型列表";
echo "        async function loadModels() {";
echo "            try {";
echo "                const response = await fetch(\'config.php\');";
echo "                if (!response.ok) {";
echo "                    throw new Error(`HTTP error! status: ${response.status}`);";
echo "                }";
echo "                const models = await response.json();";
echo "                const modelSelect = document.getElementById(\'model\');";
echo "                ";
echo "                // 清空现有选项";
echo "                modelSelect.innerHTML = \'\';";
echo "                ";
echo "                // 添加新选项";
echo "                models.forEach(model => {";
echo "                    const option = document.createElement(\'option\');";
echo "                    option.value = model.value;";
echo "                    option.textContent = model.label;";
echo "                    if (model.value === \'Flux-Dev\') {";
echo "                        option.selected = true;";
echo "                    }";
echo "                    modelSelect.appendChild(option);";
echo "                });";
echo "            } catch (error) {";
echo "                console.error(\'获取模型列表失败:\', error);";
echo "                alert(\'获取模型列表失败，请刷新页面重试\');";
echo "            }";
echo "        }";
echo "";
echo "        // 生成随机种子";
echo "        function generateRandomSeed() {";
echo "            return Math.floor(Math.random() * 100000000);";
echo "        }";
echo "";
echo "        // 保存历史记录到localStorage";
echo "        function saveToHistory(imageUrl, prompt) {";
echo "            const history = JSON.parse(localStorage.getItem(\'dreamifyHistory\') || \'[]\');";
echo "            history.unshift({";
echo "                id: Date.now(),";
echo "                imageUrl,";
echo "                prompt,";
echo "                timestamp: new Date().toISOString()";
echo "            });";
echo "            ";
echo "            // 限制历史记录数量为10";
echo "            if (history.length > 10) {";
echo "                history.pop();";
echo "            }";
echo "            ";
echo "            localStorage.setItem(\'dreamifyHistory\', JSON.stringify(history));";
echo "            updateHistoryDisplay();";
echo "        }";
echo "";
echo "        // 更新历史记录显示";
echo "        function updateHistoryDisplay() {";
echo "            const historyContainer = document.getElementById(\'historyContainer\');";
echo "            const history = JSON.parse(localStorage.getItem(\'dreamifyHistory\') || \'[]\');";
echo "            ";
echo "            if (history.length === 0) {";
echo "                historyContainer.innerHTML = `";
echo "                    <div class=\"text-center text-gray-500 py-8\">";
echo "                        <i class=\"fa fa-clock-o text-3xl mb-2\"></i>";
echo "                        <p>暂无生成历史</p>";
echo "                    </div>";
echo "                `;";
echo "                return;";
echo "            }";
echo "            ";
echo "            historyContainer.innerHTML = \'\';";
echo "            ";
echo "            history.forEach(item => {";
echo "                const historyItem = document.createElement(\'div\');";
echo "                historyItem.className = \'border border-gray-200 rounded-lg overflow-hidden flex flex-col sm:flex-row\';";
echo "                historyItem.innerHTML = `";
echo "                    <div class=\"sm:w-1/4\">";
echo "                        <img src=\"${item.imageUrl}\" alt=\"历史生成图像\" class=\"w-full h-32 sm:h-full object-cover\">";
echo "                    </div>";
echo "                    <div class=\"sm:w-3/4 p-4\">";
echo "                        <div class=\"flex justify-between items-start\">";
echo "                            <h3 class=\"font-medium\">生成于 ${new Date(item.timestamp).toLocaleString()}</h3>";
echo "                            <button class=\"text-primary hover:text-primary/80 text-sm transition-colors\" onclick=\"loadHistoryImage(\'${item.imageUrl}\', \'${escapeHTML(item.prompt)}\')\">";
echo "                                <i class=\"fa fa-eye mr-1\"></i> 查看";
echo "                            </button>";
echo "                        </div>";
echo "                        <p class=\"text-sm text-gray-600 mt-2 line-clamp-2\">${item.prompt}</p>";
echo "                    </div>";
echo "                `;";
echo "                historyContainer.appendChild(historyItem);";
echo "            });";
echo "        }";
echo "";
echo "        // 加载历史图像";
echo "        function loadHistoryImage(imageUrl, prompt) {";
echo "            document.getElementById(\'generatedImage\').src = imageUrl;";
echo "            document.getElementById(\'resultPrompt\').textContent = unescapeHTML(prompt);";
echo "            document.getElementById(\'resultContainer\').classList.remove(\'hidden\');";
echo "            document.getElementById(\'errorContainer\').classList.add(\'hidden\');";
echo "        }";
echo "";
echo "        // 辅助函数：转义HTML";
echo "        function escapeHTML(str) {";
echo "            return str";
echo "                .replace(/&/g, \'&amp;\')";
echo "                .replace(/</g, \'&lt;\')";
echo "                .replace(/>/g, \'&gt;\')";
echo "                .replace(/\"/g, \'&quot;\')";
echo "                .replace(/\'/g, \'&#039;\');";
echo "        }";
echo "";
echo "        // 辅助函数：反转义HTML";
echo "        function unescapeHTML(str) {";
echo "            return str";
echo "                .replace(/&amp;/g, \'&\')";
echo "                .replace(/&lt;/g, \'<\')";
echo "                .replace(/&gt;/g, \'>\')";
echo "                .replace(/&quot;/g, \'\"\')";
echo "                .replace(/&#039;/g, \"\'\");";
echo "        }";
echo "";
echo "        // 页面加载时初始化";
echo "        document.addEventListener(\'DOMContentLoaded\', function() {";
echo "            loadModels();";
echo "            updateHistoryDisplay();";
echo "            ";
echo "            // 随机种子按钮事件";
echo "            document.getElementById(\'randomSeedBtn\').addEventListener(\'click\', function() {";
echo "                document.getElementById(\'seed\').value = generateRandomSeed();";
echo "            });";
echo "            ";
echo "            // 表单提交事件";
echo "            document.getElementById(\'generationForm\').addEventListener(\'submit\', async function(e) {";
echo "                e.preventDefault();";
echo "                ";
echo "                // 显示加载状态";
echo "                document.getElementById(\'loadingIndicator\').classList.remove(\'hidden\');";
echo "                document.getElementById(\'resultContainer\').classList.add(\'hidden\');";
echo "                document.getElementById(\'errorContainer\').classList.add(\'hidden\');";
echo "                ";
echo "                // 收集表单数据";
echo "                const formData = {";
echo "                    prompt: document.getElementById(\'prompt\').value,";
echo "                    width: parseInt(document.getElementById(\'width\').value),";
echo "                    height: parseInt(document.getElementById(\'height\').value),";
echo "                    steps: parseInt(document.getElementById(\'steps\').value),";
echo "                    seed: parseInt(document.getElementById(\'seed\').value),";
echo "                    batch_size: parseInt(document.getElementById(\'batch_size\').value),";
echo "                    model: document.getElementById(\'model\').value,";
echo "                    images: []";
echo "                };";
echo "                ";
echo "                try {";
echo "                    // 发送请求到后端";
echo "                    const response = await fetch(\'generate.php\', {";
echo "                        method: \'POST\',";
echo "                        headers: {";
echo "                            \'Content-Type\': \'application/json\'";
echo "                        },";
echo "                        body: JSON.stringify(formData)";
echo "                    });";
echo "                    ";
echo "                    if (!response.ok) {";
echo "                        throw new Error(`HTTP error! status: ${response.status}`);";
echo "                    }";
echo "                    ";
echo "                    const result = await response.json();";
echo "                    ";
echo "                    if (result.error) {";
echo "                        throw new Error(result.error);";
echo "                    }";
echo "                    ";
echo "                    // 显示结果";
echo "                    document.getElementById(\'generatedImage\').src = result.imageUrl;";
echo "                    document.getElementById(\'resultPrompt\').textContent = formData.prompt;";
echo "                    document.getElementById(\'resultContainer\').classList.remove(\'hidden\');";
echo "                    ";
echo "                    // 保存到历史记录";
echo "                    saveToHistory(result.imageUrl, formData.prompt);";
echo "                } catch (error) {";
echo "                    console.error(\'生成图像失败:\', error);";
echo "                    document.getElementById(\'errorMessage\').textContent = error.message || \'生成图像时发生错误\';";
echo "                    document.getElementById(\'errorContainer\').classList.remove(\'hidden\');";
echo "                } finally {";
echo "                    // 隐藏加载状态";
echo "                    document.getElementById(\'loadingIndicator\').classList.add(\'hidden\');";
echo "                }";
echo "            });";
echo "            ";
echo "            // 下载按钮事件";
echo "            document.getElementById(\'downloadBtn\').addEventListener(\'click\', function() {";
echo "                const img = document.getElementById(\'generatedImage\');";
echo "                const link = document.createElement(\'a\');";
echo "                link.download = \'dreamify-image.png\';";
echo "                link.href = img.src;";
echo "                link.click();";
echo "            });";
echo "        });";
echo "    </script>";
echo "</body>";
echo "</html>";
echo "    ";
?>
